### PR TITLE
Fixed workspace install and missing prisma binary

### LINKED ISSUE #85: An unexpected error occurred: "https://registry.yarnpkg.com/@calcom%2flib: Not found".
I have done a fix my moving the prisma to another location but another issue occur.

 ---> Running in f6a7a687a701
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@calcom%2flib: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/calendso/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'calendso' failed to build : The command '/bin/sh -c yarn install' returned a non-zero code: 1
❯

Please suggest the solution

### PR DESCRIPTION
**Pull request by philprime**
This is an updated version of #94 

This should close #85, #91, #92

### CODE REVIEW

**Comment by philprime** [comment]
CC: @krumware

**Comment by philprime** [comment]
Instead of copying every single package.json, we could also copy the full `packages` folder and delete all irrelevant files. But this would remove the purpose of layer caching, as unchanged `package.json` should reuse previous layers.

```dockerfile
COPY calendso/packages ./packages
RUN find packages -type f ! -name 'package.json' -delete
```

**Comment by alonsomoya** [comment]
> This should close #85, #91, #92
++ I confirm this unblocks fresh installations (as without it I get the following)
```
[2/5] Resolving packages...
error Couldn't find package "@calcom/app-store@*" required by "@calcom/web@1.4.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by philprime** [comment]
Rebased the PR on the latest commit on branch `main`

**Comment by krumware** [comment]
@philprime can you add the calendso/turbo.json copy to the first step (line 6). install is complaining that it's missing.
`COPY calendso/package.json calendso/yarn.lock calendso/turbo.json ./`

Also, let's use the `COPY calendso/packages ./packages` shortcut. There are more packages being added than we can keep up with, and I'll work with the calcom team to add notification of new package folders to the release workflow

**Comment by krumware** [comment]
I have another branch for some refactor going, but don't want to lose or discard your work. it's much appreciated!

**Review by krumware — APPROVED** [review]

**Pull request merged**
