### PR TITLE
fix: makes docker usable for production

### PR DESCRIPTION
**Pull request by adrian-d-hidalgo**
## What does this PR do?

This PR removes unnecessary code and processes and updates some commands to build a production bundle.

This PR complements https://github.com/calcom/cal.com/pull/12686, so it should be updated to the latest commit to work correctly once merged.

Fixes [#12032](https://github.com/calcom/cal.com/issues/12032)

## Type of change

- [x] chore (non-breaking change which adds functionality)

## How should this be tested?

- clone repository `git clone --recursive https://github.com/calcom/docker.git`
- make a copy of .env and .env.appStore from calcom examples, place them into the root docker project directory, and override whit your environment variables 
- make a copy from .env.database-example > .env.database
- run `docker-compose up`

### CODE REVIEW

**Comment by emrysal** [comment]
@krumware for visibility.

The Docker build issues (or rather, having to rebuild after doing a docker pull to get the right env vars sorted) is an application issue; Could you elaborate more how this aims to resolve that?

**Comment by PIG208** [comment]
Would it be helpful to revive #147?

**Comment by adrian-d-hidalgo** [comment]
> @krumware for visibility.
> 
> The Docker build issues (or rather, having to rebuild after doing a docker pull to get the right env vars sorted) is an application issue; Could you elaborate more how this aims to resolve that?

Hi @emrysal, I just pushed an update; the main goal now is that the image build process installs yarn dependencies and executes yarn build to generate the project bundle using mock environment variables (if you don't have them during the build process fails, this can later be overriden).

Finally you have the Docker image built you can bind .env files to pass your runtime variables like this:

```bash
docker run -p 127.0.0.1:3000:3000/tcp --volume "$(pwd)/.env:/calcom/.env" --volume "$(pwd)/.env.appStore:/calcom/.env.appStore"
```

With this new approach you can have an Official Docker Image that can be deployed individually that doesn't get generated with env keys, this satisfies with the issue that env variables should be runtime only now.

**Comment by compgeniuses** [comment]
looking forward to the implementations of these

**Comment by compgeniuses** [comment]
so the other PR seems to have closed in favour of this https://github.com/calcom/cal.com/pull/13541

**Comment by komali2** [comment]
If I copy this PR, and follow the instructions, and then run `docker compose up`, i get this error: 

```
[+] Building 6.2s (3/3) FINISHED                                                                                                    docker:default
 => [calcom internal] load build definition from Dockerfile                                                                                   0.9s
 => => transferring dockerfile: 1.45kB                                                                                                        0.0s
 => [calcom internal] load metadata for docker.io/library/node:18                                                                             0.1s
 => ERROR [calcom internal] load metadata for docker.io/library/builder-two:latest                                                            1.8s
------
 > [calcom internal] load metadata for docker.io/library/builder-two:latest:
------
failed to solve: builder-two: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Pull request closed without merging**
