### PR TITLE
Use Scarf endpoint for Cal.com container

### PR DESCRIPTION
**Pull request by arjundevarajan**
Update docker-compose.yaml to utilize Scarf endpoint for the Cal.com container. Scarf is a tool that allows maintainers to track open-source project adoption and usage metrics. Updating the image references in the `docker-compose.yaml` file to redirect through Scarf first lets these metrics be collected for product improvement

### CODE REVIEW

**Comment by krumware** [comment]
This can be done via a docker-compose.override.yml file, but I'm not sure if it belongs in the base

**Comment by aviaviavi** [comment]
The intention of this change is for the Cal.com team to have better visibility into the download metrics of the Docker installation. That's most effective when it's instrumented as a default, rather than being patched as an override.

**Comment by PeerRich** [comment]
fyi: i asked @aviaviavi to raise a PR, im just not sure what the implications are of merging this

**Comment by aviaviavi** [comment]
To give a bit more explanation: the idea is that when the Docker Compose installation is invoked, the `calendso` container will be downloaded from Cal.com's Scarf endpoint, where the client is then seamlessly redirected to Docker Hub. There is no user experience impact from this change but it does ensure anonymized download metrics are visible to your org.

**Comment by krumware** [comment]
understood, thanks for the context!
we're moving to github packages. what we'll the URL look like for that?

**Comment by aviaviavi** [comment]
One of the cool parts is that you won't actually have to update this URL when you make that change. You can just update the configuration within Scarf to configure redirects to point to `ghcr.io`, and it will immediately start sending the traffic there. You'll never need to update the public URL that end-users download, no matter how many times you switch container registries in the future.

**Comment by arjundevarajan** [comment]
Hi @krumware were there any other roadblocks here? Let us know if there's anything we can help with!

**Comment by krumware** [comment]
sent him a note, thanks!

**Comment by PeerRich** [comment]
created a scarf account: peer@cal.com, waiting to get admin access and will add @krumware then

**Comment by arjundevarajan** [comment]
Hi @PeerRich you are now the owner of the Calcom organization on Scarf, you should be able to add other users!

**Comment by PeerRich** [comment]
added krum

**Review by krumware — APPROVED** [review]

**Comment by krumware** [comment]
@arjundevarajan we've updated the config on scarf to pull from the new docker repository location of calcom/cal.com, but the package in scarf still shows the calendso/calendso pull command.
Can you advise on how to change that?

**Comment by PeerRich** [comment]
CleanShot 2022-12-18 at 11 40 41
here it still says calendso/calendso

**Comment by PeerRich** [comment]
should I create a new package? 
CleanShot 2022-12-18 at 11 42 01

**Comment by PeerRich** [comment]
i dont think you can rename existing packages

**Comment by aviaviavi** [comment]
Apologies @PeerRich and @krumware you were doing the right thing but it looks like there was a bug on our side causing the pull command to not update as expected. It's updated now.

**Comment by aviaviavi** [comment]
Keep in mind that you have the calendso/* collection in Scarf set up so the current docker compose file pointing to the old name still continues to work. When you're ready to move to GHCR we can move everything over at once.

**Comment by krumware** [comment]
We actually were able to obtain the calcom dockerhub organization, so we're hoping to eliminate the usage of `calendso` altogether. Is this possible?

**Comment by arjundevarajan** [comment]
@krumware the pull command is updated! 
Screen Shot 2022-12-19 at 11 08 19 AM

**Comment by krumware** [comment]
thanks! updated on this end

**Comment by PeerRich** [comment]
thank you @arjundevarajan

**Comment by arjundevarajan** [comment]
@krumware what do you want the behavior there to be when someone tries to download the old `calendso` container from Scarf? Would you want it to break? Or to continue to go to the old Calendso container?

**Comment by krumware** [comment]
If someone still has the old calendar scarf.sh endpoint we would want that to pull from the updated calcom/cal.com docker hub 👍

**Comment by arjundevarajan** [comment]
Unfortunately this is not possible because container clients use that image name to compute a signature, so serving `cal.com` containers to users asking for `calendso` causes the clients to reject the download

**Comment by krumware** [comment]
Let's continue to send requests through to dockerhub, we don't want to break anyone. That's good to know on the naming. We're going to keep updating the calendso namespace, with a deprecation notice.

Thanks!

**Comment by arjundevarajan** [comment]
Sounds good. It looks like you also have an additional empty package set up on Scarf with a typo (calenSDo instead of calenDSo) - want me to go ahead and delete that incorrect one?

Screen Shot 2022-12-20 at 2 48 55 PM

**Comment by PeerRich** [comment]
> Sounds good. It looks like you also have an additional empty package set up on Scarf with a typo (calenSDo instead of calenDSo) - want me to go ahead and delete that incorrect one?
> 
> Screen Shot 2022-12-20 at 2 48 55 PM

yes please

**Comment by arjundevarajan** [comment]
Done!

**Pull request merged**
