### PR TITLE
Fix markdownlint issues

### PR DESCRIPTION
**Pull request by jokay**
Fixes the [markdownlint](https://github.com/DavidAnson/markdownlint) issues in `SECURITY.md`.

```sh
SECURITY.md:1 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "# Security"]
SECURITY.md:2:10 MD034/no-bare-urls Bare URL used [Context: "security@cal.com"]
SECURITY.md:6:81 MD013/line-length Line length [Expected: 80; Actual: 170]
SECURITY.md:8:81 MD013/line-length Line length [Expected: 80; Actual: 202]
SECURITY.md:10:32 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
SECURITY.md:12:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:13:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:14:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:15:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:16:81 MD013/line-length Line length [Expected: 80; Actual: 118]
SECURITY.md:16:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:17:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:18:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:19:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:20:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:22:27 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
SECURITY.md:24:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:25:81 MD013/line-length Line length [Expected: 80; Actual: 142]
SECURITY.md:25:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:26:81 MD013/line-length Line length [Expected: 80; Actual: 209]
SECURITY.md:26:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:27:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:28:81 MD013/line-length Line length [Expected: 80; Actual: 134]
SECURITY.md:28:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:29:81 MD013/line-length Line length [Expected: 80; Actual: 298]
SECURITY.md:29:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:31:19 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
SECURITY.md:33:81 MD013/line-length Line length [Expected: 80; Actual: 124]
SECURITY.md:33:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:34:81 MD013/line-length Line length [Expected: 80; Actual: 119]
SECURITY.md:34:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:35:81 MD013/line-length Line length [Expected: 80; Actual: 139]
SECURITY.md:35:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:36:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:37:81 MD013/line-length Line length [Expected: 80; Actual: 153]
SECURITY.md:37:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
SECURITY.md:38:81 MD013/line-length Line length [Expected: 80; Actual: 167]
SECURITY.md:38:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]
```

### CODE REVIEW

**Comment by krumware** [comment]
please provide a markdownlint config with the proposed changes

**Comment by jokay** [comment]
The check was executed without any specific config, like this:

```sh
user@host:~/GitHub/docker-calcom$ markdownlint SECURITY.md
```

**Comment by jokay** [comment]
The check was executed without any specific config, like this:

```sh
user@host:~/GitHub/docker-calcom$ markdownlint SECURITY.md
```

**Comment by krumware** [comment]
understood, but if we want to introduce it as tool here then we need to specify a local config to override a user's default settings and help clarify the rules used here

**Comment by jokay** [comment]
I would use the default *(no config override)* but it's up to you.

**Pull request closed without merging**
